/// <reference path="../jqwidgets.d.ts" />
import { EventEmitter, ElementRef, OnChanges, SimpleChanges } from '@angular/core';
export declare class jqxPivotGridComponent implements OnChanges {
    attrSource: any;
    attrLocalization: any;
    attrScrollBarsEnabled: boolean;
    attrSelectionEnabled: boolean;
    attrMultipleSelectionEnabled: boolean;
    attrTreeStyleRows: boolean;
    attrAutoResize: boolean;
    attrItemsRenderer: (pivotItem: any) => string;
    attrCellsRenderer: (pivotCell: any) => string;
    attrWidth: string | number;
    attrHeight: string | number;
    autoCreate: boolean;
    properties: string[];
    host: any;
    elementRef: ElementRef;
    widgetObject: jqwidgets.jqxPivotGrid;
    constructor(containerElement: ElementRef);
    ngOnInit(): void;
    ngOnChanges(changes: SimpleChanges): boolean;
    arraysEqual(attrValue: any, hostValue: any): boolean;
    manageAttributes(): any;
    moveClasses(parentEl: HTMLElement, childEl: HTMLElement): void;
    moveStyles(parentEl: HTMLElement, childEl: HTMLElement): void;
    createComponent(options?: any): void;
    createWidget(options?: any): void;
    __updateRect__(): void;
    setOptions(options: any): void;
    source(arg?: any): any;
    localization(arg?: any): any;
    scrollBarsEnabled(arg?: boolean): any;
    selectionEnabled(arg?: boolean): any;
    multipleSelectionEnabled(arg?: boolean): any;
    treeStyleRows(arg?: boolean): any;
    autoResize(arg?: boolean): any;
    itemsRenderer(arg?: (pivotItem: any) => string): any;
    cellsRenderer(arg?: (pivotCell: any) => string): any;
    getInstance(): any;
    refresh(): void;
    getPivotRows(): jqwidgets.PivotGridRows;
    getPivotColumns(): jqwidgets.PivotGridColumns;
    getPivotCells(): jqwidgets.PivotGridCells;
    onPivotitemexpanding: EventEmitter<{}>;
    onPivotitemexpanded: EventEmitter<{}>;
    onPivotitemcollapsing: EventEmitter<{}>;
    onPivotitemcollapsed: EventEmitter<{}>;
    onSortchanging: EventEmitter<{}>;
    onSortchanged: EventEmitter<{}>;
    onSortremoving: EventEmitter<{}>;
    onSortremoved: EventEmitter<{}>;
    onPivotitemselectionchanged: EventEmitter<{}>;
    onPivotcellmousedown: EventEmitter<{}>;
    onPivotcellmouseup: EventEmitter<{}>;
    onPivotcellclick: EventEmitter<{}>;
    onPivotcelldblclick: EventEmitter<{}>;
    onPivotitemmousedown: EventEmitter<{}>;
    onPivotitemmouseup: EventEmitter<{}>;
    onPivotitemclick: EventEmitter<{}>;
    onPivotitemdblclick: EventEmitter<{}>;
    __wireEvents__(): void;
}
