/// <reference path="../jqwidgets.d.ts" />
import { EventEmitter, ElementRef, OnChanges, SimpleChanges } from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
export declare class jqxNumberInputComponent implements ControlValueAccessor, OnChanges {
    attrAllowNull: boolean;
    attrDecimal: number | string;
    attrDisabled: boolean;
    attrDecimalDigits: number | string;
    attrDecimalSeparator: number | string;
    attrDigits: number | string;
    attrGroupSeparator: string;
    attrGroupSize: number | string;
    attrInputMode: any;
    attrMin: number | string;
    attrMax: number | string;
    attrNegativeSymbol: string;
    attrPlaceHolder: number | string;
    attrPromptChar: any;
    attrRtl: boolean;
    attrReadOnly: boolean;
    attrSpinMode: any;
    attrSpinButtons: boolean;
    attrSpinButtonsWidth: number;
    attrSpinButtonsStep: number | string;
    attrSymbol: string;
    attrSymbolPosition: any;
    attrTextAlign: any;
    attrTemplate: any;
    attrTheme: string;
    attrValue: number | string;
    attrWidth: string | number;
    attrHeight: string | number;
    autoCreate: boolean;
    properties: string[];
    host: any;
    elementRef: ElementRef;
    widgetObject: jqwidgets.jqxNumberInput;
    private onTouchedCallback;
    private onChangeCallback;
    constructor(containerElement: ElementRef);
    ngOnInit(): void;
    ngOnChanges(changes: SimpleChanges): boolean;
    arraysEqual(attrValue: any, hostValue: any): boolean;
    manageAttributes(): any;
    moveClasses(parentEl: HTMLElement, childEl: HTMLElement): void;
    moveStyles(parentEl: HTMLElement, childEl: HTMLElement): void;
    createComponent(options?: any): void;
    createWidget(options?: any): void;
    __updateRect__(): void;
    writeValue(value: any): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    setOptions(options: any): void;
    allowNull(arg?: boolean): any;
    decimal(arg?: number | string): any;
    disabled(arg?: boolean): any;
    decimalDigits(arg?: number | string): any;
    decimalSeparator(arg?: number | string): any;
    digits(arg?: number | string): any;
    groupSeparator(arg?: string): any;
    groupSize(arg?: number | string): any;
    height(arg?: string | number): any;
    inputMode(arg?: string): any;
    min(arg?: number | string): any;
    max(arg?: number | string): any;
    negativeSymbol(arg?: string): any;
    placeHolder(arg?: number | string): any;
    promptChar(arg?: string): any;
    rtl(arg?: boolean): any;
    readOnly(arg?: boolean): any;
    spinMode(arg?: string): any;
    spinButtons(arg?: boolean): any;
    spinButtonsWidth(arg?: number): any;
    spinButtonsStep(arg?: number | string): any;
    symbol(arg?: string): any;
    symbolPosition(arg?: string): any;
    textAlign(arg?: string): any;
    template(arg?: string): any;
    theme(arg?: string): any;
    value(arg?: number | string): any;
    width(arg?: string | number): any;
    clear(): void;
    destroy(): void;
    focus(): void;
    getDecimal(): number;
    setDecimal(index: number | string): void;
    val(value?: number | string): any;
    onChange: EventEmitter<{}>;
    onTextchanged: EventEmitter<{}>;
    onValueChanged: EventEmitter<{}>;
    __wireEvents__(): void;
}
