/// <reference path="../jqwidgets.d.ts" />
import { EventEmitter, ElementRef, OnChanges, SimpleChanges } from '@angular/core';
export declare class jqxDropDownButtonComponent implements OnChanges {
    attrAnimationType: string;
    attrArrowSize: number;
    attrAutoOpen: boolean;
    attrCloseDelay: number;
    attrDisabled: boolean;
    attrDropDownHorizontalAlignment: string;
    attrDropDownVerticalAlignment: string;
    attrDropDownWidth: number | string;
    attrEnableBrowserBoundsDetection: boolean;
    attrInitContent: () => void;
    attrOpenDelay: number;
    attrPopupZIndex: number;
    attrRtl: boolean;
    attrTemplate: string;
    attrTheme: string;
    attrWidth: string | number;
    attrHeight: string | number;
    autoCreate: boolean;
    properties: string[];
    host: any;
    elementRef: ElementRef;
    widgetObject: jqwidgets.jqxDropDownButton;
    constructor(containerElement: ElementRef);
    ngOnInit(): void;
    ngOnChanges(changes: SimpleChanges): boolean;
    arraysEqual(attrValue: any, hostValue: any): boolean;
    manageAttributes(): any;
    moveClasses(parentEl: HTMLElement, childEl: HTMLElement): void;
    moveStyles(parentEl: HTMLElement, childEl: HTMLElement): void;
    createComponent(options?: any): void;
    createWidget(options?: any): void;
    __updateRect__(): void;
    setOptions(options: any): void;
    animationType(arg?: string): string;
    arrowSize(arg?: number): number;
    autoOpen(arg?: boolean): boolean;
    closeDelay(arg?: number): number;
    disabled(arg?: boolean): boolean;
    dropDownHorizontalAlignment(arg?: string): string;
    dropDownVerticalAlignment(arg?: string): string;
    dropDownWidth(arg?: number | string): number | string;
    enableBrowserBoundsDetection(arg?: boolean): boolean;
    height(arg?: string | number): string | number;
    initContent(arg?: () => void): () => void;
    openDelay(arg?: number): number;
    popupZIndex(arg?: number): number;
    rtl(arg?: boolean): boolean;
    template(arg?: string): string;
    theme(arg?: string): string;
    width(arg?: string | number): string | number;
    close(): void;
    destroy(): void;
    focus(): void;
    getContent(): any;
    isOpened(): boolean;
    open(): void;
    setContent(content: string): void;
    onClose: EventEmitter<any>;
    onOpen: EventEmitter<any>;
    __wireEvents__(): void;
}
