/// <reference path="../jqwidgets.d.ts" />
import { EventEmitter, ElementRef, OnChanges, SimpleChanges } from '@angular/core';
export declare class jqxDockingComponent implements OnChanges {
    attrCookies: boolean;
    attrCookieOptions: jqwidgets.DockingCookieOptions;
    attrDisabled: boolean;
    attrFloatingWindowOpacity: number;
    attrKeyboardNavigation: boolean;
    attrMode: any;
    attrOrientation: any;
    attrRtl: boolean;
    attrTheme: string;
    attrWindowsMode: jqwidgets.DockingWindowsMode;
    attrWindowsOffset: number;
    attrWidth: string | number;
    attrHeight: string | number;
    autoCreate: boolean;
    properties: string[];
    host: any;
    elementRef: ElementRef;
    widgetObject: jqwidgets.jqxDocking;
    constructor(containerElement: ElementRef);
    ngOnInit(): void;
    ngOnChanges(changes: SimpleChanges): boolean;
    arraysEqual(attrValue: any, hostValue: any): boolean;
    manageAttributes(): any;
    moveClasses(parentEl: HTMLElement, childEl: HTMLElement): void;
    moveStyles(parentEl: HTMLElement, childEl: HTMLElement): void;
    createComponent(options?: any): void;
    createWidget(options?: any): void;
    __updateRect__(): void;
    setOptions(options: any): void;
    cookies(arg?: boolean): any;
    cookieOptions(arg?: jqwidgets.DockingCookieOptions): any;
    disabled(arg?: boolean): any;
    floatingWindowOpacity(arg?: number): any;
    height(arg?: number | string): any;
    keyboardNavigation(arg?: boolean): any;
    mode(arg?: string): any;
    orientation(arg?: string): any;
    rtl(arg?: boolean): any;
    theme(arg?: string): any;
    width(arg?: number | string): any;
    windowsMode(arg?: jqwidgets.DockingWindowsMode): any;
    windowsOffset(arg?: number): any;
    addWindow(windowId: string, mode: any, panel: number, position: any): void;
    closeWindow(windowId: string): void;
    collapseWindow(windowId: string): void;
    destroy(): void;
    disableWindowResize(windowId: string): void;
    disable(): void;
    exportLayout(): string;
    enable(): void;
    expandWindow(windowId: string): void;
    enableWindowResize(windowId: string): void;
    focus(): void;
    hideAllCloseButtons(): void;
    hideAllCollapseButtons(): void;
    hideCollapseButton(windowId: string): void;
    hideCloseButton(windowId: string): void;
    importLayout(Json: string): void;
    move(windowId: string, panel: number, position: number): void;
    pinWindow(windowId: string): void;
    setWindowMode(windowId: string, mode: any): void;
    showCloseButton(windowId: string): void;
    showCollapseButton(windowId: string): void;
    setWindowPosition(windowId: string, top: any, left: number): void;
    showAllCloseButtons(): void;
    showAllCollapseButtons(): void;
    unpinWindow(windowId: string): void;
    onDragStart: EventEmitter<{}>;
    onDragEnd: EventEmitter<{}>;
    __wireEvents__(): void;
}
