/// <reference path="../jqwidgets.d.ts" />
import { AfterViewInit, AfterViewChecked, EventEmitter, ElementRef, OnChanges, SimpleChanges } from '@angular/core';
export declare class jqxTreeGridComponent implements OnChanges, AfterViewInit, AfterViewChecked {
    attrAltRows: boolean;
    attrAutoRowHeight: boolean;
    attrAggregatesHeight: number;
    attrAutoShowLoadElement: boolean;
    attrCheckboxes: boolean;
    attrColumnsHeight: number;
    attrColumns: Array<any>;
    attrColumnGroups: Array<any>;
    attrColumnsResize: boolean;
    attrColumnsReorder: boolean;
    attrDisabled: boolean;
    attrEditable: boolean;
    attrEditSettings: jqwidgets.TreeGridEditSettings;
    attrExportSettings: jqwidgets.TreeGridExportSettings;
    attrEnableHover: boolean;
    attrEnableBrowserSelection: boolean;
    attrFilterable: boolean;
    attrFilterHeight: number;
    attrFilterMode: string;
    attrHierarchicalCheckboxes: boolean;
    attrIcons: any;
    attrIncrementalSearch: boolean;
    attrLocalization: any;
    attrPagerHeight: number;
    attrPageSize: number;
    attrPageSizeOptions: Array<number | string>;
    attrPageable: boolean;
    attrPagerPosition: string;
    attrPagerMode: string;
    attrPageSizeMode: string;
    attrPagerButtonsCount: number;
    attrPagerRenderer: () => any;
    attrReady: () => void;
    attrRowDetails: boolean;
    attrRowDetailsRenderer: (key: jqwidgets.TreeGridRowDetailsRenderer['key'], dataRow: jqwidgets.TreeGridRowDetailsRenderer['dataRow']) => any;
    attrRenderToolbar: (toolBar?: jqwidgets.TreeGridRenderToolbar['toolbar']) => void;
    attrRenderStatusBar: (statusBar?: jqwidgets.TreeGridRenderStatusBar['statusbar']) => void;
    attrRendering: () => void;
    attrRendered: () => void;
    attrRtl: boolean;
    attrSource: any;
    attrSortable: boolean;
    attrShowAggregates: boolean;
    attrShowSubAggregates: boolean;
    attrShowToolbar: boolean;
    attrShowStatusbar: boolean;
    attrStatusBarHeight: number;
    attrScrollBarSize: number;
    attrSelectionMode: string;
    attrShowHeader: boolean;
    attrTheme: string;
    attrToolbarHeight: number;
    attrVirtualModeCreateRecords: (expandedRecord?: any, done?: any) => void;
    attrVirtualModeRecordCreating: (record?: any) => any;
    attrWidth: string | number;
    attrHeight: string | number;
    autoCreate: boolean;
    properties: string[];
    host: any;
    elementRef: ElementRef;
    widgetObject: jqwidgets.jqxTreeGrid;
    content: String;
    container: HTMLDivElement;
    constructor(containerElement: ElementRef);
    ngOnInit(): void;
    ngAfterViewInit(): void;
    ngAfterViewChecked(): void;
    ngOnChanges(changes: SimpleChanges): boolean;
    arraysEqual(attrValue: any, hostValue: any): boolean;
    manageAttributes(): any;
    moveClasses(parentEl: HTMLElement, childEl: HTMLElement): void;
    moveStyles(parentEl: HTMLElement, childEl: HTMLElement): void;
    createComponent(options?: any): void;
    createWidget(options?: any): void;
    __updateRect__(): void;
    setOptions(options: any): void;
    altRows(arg?: boolean): boolean;
    autoRowHeight(arg?: boolean): boolean;
    aggregatesHeight(arg?: number): number;
    autoShowLoadElement(arg?: boolean): boolean;
    checkboxes(arg?: boolean): boolean;
    columnsHeight(arg?: number): number;
    columns(arg?: Array<any>): Array<any>;
    columnGroups(arg?: Array<any>): Array<any>;
    columnsResize(arg?: boolean): boolean;
    columnsReorder(arg?: boolean): boolean;
    disabled(arg?: boolean): boolean;
    editable(arg?: boolean): boolean;
    editSettings(arg?: jqwidgets.TreeGridEditSettings): jqwidgets.TreeGridEditSettings;
    exportSettings(arg?: jqwidgets.TreeGridExportSettings): jqwidgets.TreeGridExportSettings;
    enableHover(arg?: boolean): boolean;
    enableBrowserSelection(arg?: boolean): boolean;
    filterable(arg?: boolean): boolean;
    filterHeight(arg?: number): number;
    filterMode(arg?: string): string;
    height(arg?: number | string): number | string;
    hierarchicalCheckboxes(arg?: boolean): boolean;
    icons(arg?: any): any;
    incrementalSearch(arg?: boolean): boolean;
    localization(arg?: any): any;
    pagerHeight(arg?: number): number;
    pageSize(arg?: number): number;
    pageSizeOptions(arg?: Array<number | string>): Array<number | string>;
    pageable(arg?: boolean): boolean;
    pagerPosition(arg?: string): string;
    pagerMode(arg?: string): string;
    pageSizeMode(arg?: string): string;
    pagerButtonsCount(arg?: number): number;
    pagerRenderer(arg?: () => any): () => any;
    ready(arg?: () => void): () => void;
    rowDetails(arg?: boolean): boolean;
    rowDetailsRenderer(arg?: (key: jqwidgets.TreeGridRowDetailsRenderer['key'], dataRow: jqwidgets.TreeGridRowDetailsRenderer['dataRow']) => any): (key: jqwidgets.TreeGridRowDetailsRenderer['key'], dataRow: jqwidgets.TreeGridRowDetailsRenderer['dataRow']) => any;
    renderToolbar(arg?: (toolBar?: jqwidgets.TreeGridRenderToolbar['toolbar']) => void): (toolBar?: jqwidgets.TreeGridRenderToolbar['toolbar']) => void;
    renderStatusBar(arg?: (statusBar?: jqwidgets.TreeGridRenderStatusBar['statusbar']) => void): (statusBar?: jqwidgets.TreeGridRenderStatusBar['statusbar']) => void;
    rendering(arg?: () => void): () => void;
    rendered(arg?: () => void): () => void;
    rtl(arg?: boolean): boolean;
    source(arg?: any): any;
    sortable(arg?: boolean): boolean;
    showAggregates(arg?: boolean): boolean;
    showSubAggregates(arg?: boolean): boolean;
    showToolbar(arg?: boolean): boolean;
    showStatusbar(arg?: boolean): boolean;
    statusBarHeight(arg?: number): number;
    scrollBarSize(arg?: number): number;
    selectionMode(arg?: string): string;
    showHeader(arg?: boolean): boolean;
    theme(arg?: string): string;
    toolbarHeight(arg?: number): number;
    width(arg?: string | number): string | number;
    virtualModeCreateRecords(arg?: (expandedRecord?: any, done?: any) => void): (expandedRecord?: any, done?: any) => void;
    virtualModeRecordCreating(arg?: (record?: any) => any): (record?: any) => any;
    addRow(rowKey: number | string | null, rowData: any, rowPosition: string, parent?: string): void;
    addFilter(dataField: string, filerGroup: any): void;
    applyFilters(): void;
    beginUpdate(): void;
    beginRowEdit(rowKey: number | string): void;
    beginCellEdit(rowKey: number | string, dataField: string): void;
    clearSelection(): void;
    clearFilters(): void;
    clear(): void;
    checkRow(rowKey: number | string): void;
    collapseRow(rowKey: number | string): void;
    collapseAll(): void;
    destroy(): void;
    deleteRow(rowKey: string[] | string): void;
    expandRow(rowKey: Array<number | string> | string | number): void;
    expandAll(): void;
    endUpdate(): void;
    ensureRowVisible(rowKey: number | string): void;
    endRowEdit(rowKey: number | string, cancelChanges?: boolean): void;
    endCellEdit(rowKey: number | string, dataField: string, cancelChanges?: boolean): void;
    exportData(exportDataType: any): any;
    focus(): void;
    getColumnProperty(dataField: string, propertyName: string): any;
    goToPage(pageIndex: number): void;
    goToPrevPage(): void;
    goToNextPage(): void;
    getSelection(): Array<any>;
    getKey(row: any): string;
    getRow(rowKey: number | string): jqwidgets.TreeGridGetRow;
    getRows(): Array<jqwidgets.TreeGridGetRow>;
    getCheckedRows(): Array<jqwidgets.TreeGridGetRow>;
    getView(): Array<jqwidgets.TreeGridGetRow>;
    getCellValue(rowKey: number | string, dataField: string): any;
    hideColumn(dataField: string): void;
    isBindingCompleted(): boolean;
    lockRow(rowKey: string | number | Array<number | string>): void;
    refresh(): void;
    render(): void;
    removeFilter(dataField: string): void;
    scrollOffset(top?: number, left?: number): jqwidgets.TreeGridScrollOffset;
    setColumnProperty(dataField: string, propertyName: string, propertyValue: any): void;
    showColumn(dataField: string): void;
    selectRow(rowId: string | number | Array<number | string>): void;
    setCellValue(rowId: string, dataField: string, cellValue: any): void;
    sortBy(dataField: number | string, sortOrder?: 'asc' | 'desc' | null): void;
    updating(): boolean;
    updateBoundData(): void;
    unselectRow(rowId: string | number | Array<number | string>): void;
    uncheckRow(rowId: string): void;
    updateRow(rowId: number | string, data: any): void;
    unlockRow(rowId: string | number | Array<number | string>): void;
    onBindingComplete: EventEmitter<any>;
    onCellBeginEdit: EventEmitter<any>;
    onCellEndEdit: EventEmitter<any>;
    onCellValueChanged: EventEmitter<any>;
    onColumnResized: EventEmitter<any>;
    onColumnReordered: EventEmitter<any>;
    onFilter: EventEmitter<any>;
    onPageChanged: EventEmitter<any>;
    onPageSizeChanged: EventEmitter<any>;
    onRowClick: EventEmitter<any>;
    onRowDoubleClick: EventEmitter<any>;
    onRowSelect: EventEmitter<any>;
    onRowUnselect: EventEmitter<any>;
    onRowBeginEdit: EventEmitter<any>;
    onRowEndEdit: EventEmitter<any>;
    onRowExpand: EventEmitter<any>;
    onRowCollapse: EventEmitter<any>;
    onRowCheck: EventEmitter<any>;
    onRowUncheck: EventEmitter<any>;
    onSort: EventEmitter<any>;
    __wireEvents__(): void;
}
