/// <reference path="../jqwidgets.d.ts" />
import { EventEmitter, ElementRef, OnChanges, SimpleChanges } from '@angular/core';
export declare class jqxBulletChartComponent implements OnChanges {
    attrAnimationDuration: number;
    attrBarSize: number | string;
    attrDescription: string;
    attrDisabled: boolean;
    attrLabelsFormat: any;
    attrLabelsFormatFunction: (value?: number, position?: string) => any;
    attrOrientation: any;
    attrPointer: jqwidgets.BulletChartPointer;
    attrRtl: boolean;
    attrRanges: Array<jqwidgets.BulletChartRanges>;
    attrShowTooltip: boolean;
    attrTarget: jqwidgets.BulletChartPointer;
    attrTicks: jqwidgets.BulletChartTicks;
    attrTitle: string;
    attrTooltipFormatFunction: (pointerValue: number, targetValue: number) => string;
    attrWidth: string | number;
    attrHeight: string | number;
    autoCreate: boolean;
    properties: string[];
    host: any;
    elementRef: ElementRef;
    widgetObject: jqwidgets.jqxBulletChart;
    constructor(containerElement: ElementRef);
    ngOnInit(): void;
    ngOnChanges(changes: SimpleChanges): boolean;
    arraysEqual(attrValue: any, hostValue: any): boolean;
    manageAttributes(): any;
    moveClasses(parentEl: HTMLElement, childEl: HTMLElement): void;
    moveStyles(parentEl: HTMLElement, childEl: HTMLElement): void;
    createComponent(options?: any): void;
    createWidget(options?: any): void;
    __updateRect__(): void;
    setOptions(options: any): void;
    animationDuration(arg?: number): any;
    barSize(arg?: number | string): any;
    description(arg?: string): any;
    disabled(arg?: boolean): any;
    height(arg?: string | number): any;
    labelsFormat(arg?: string): any;
    labelsFormatFunction(arg?: (value?: number, position?: string) => any): any;
    orientation(arg?: string): any;
    pointer(arg?: jqwidgets.BulletChartPointer): any;
    rtl(arg?: boolean): any;
    ranges(arg?: Array<jqwidgets.BulletChartRanges>): any;
    showTooltip(arg?: boolean): any;
    target(arg?: jqwidgets.BulletChartPointer): any;
    ticks(arg?: jqwidgets.BulletChartTicks): any;
    title(arg?: string): any;
    tooltipFormatFunction(arg?: (pointerValue: number, targetValue: number) => string): any;
    width(arg?: string | number): any;
    destroy(): void;
    render(): void;
    refresh(): void;
    val(value?: number): any;
    onChange: EventEmitter<{}>;
    __wireEvents__(): void;
}
