/// <reference path="../jqwidgets.d.ts" />
import { EventEmitter, ElementRef, OnChanges, SimpleChanges } from '@angular/core';
export declare class jqxBulletChartComponent implements OnChanges {
    attrAnimationDuration: number;
    attrBarSize: number | string;
    attrDescription: string;
    attrDisabled: boolean;
    attrLabelsFormat: string;
    attrLabelsFormatFunction: (value?: jqwidgets.BulletChartLabelsFormatFunction['value'], position?: jqwidgets.BulletChartLabelsFormatFunction['position']) => any;
    attrOrientation: string;
    attrPointer: jqwidgets.BulletChartPointer;
    attrRtl: boolean;
    attrRanges: Array<jqwidgets.BulletChartRanges>;
    attrShowTooltip: boolean;
    attrTarget: jqwidgets.BulletChartPointer;
    attrTicks: jqwidgets.BulletChartTicks;
    attrTitle: string;
    attrTooltipFormatFunction: (pointerValue?: jqwidgets.BulletChartTooltipFormatFunction['pointerValue'], targetValue?: jqwidgets.BulletChartTooltipFormatFunction['targetValue']) => string;
    attrWidth: string | number;
    attrHeight: string | number;
    autoCreate: boolean;
    properties: string[];
    host: any;
    elementRef: ElementRef;
    widgetObject: jqwidgets.jqxBulletChart;
    constructor(containerElement: ElementRef);
    ngOnInit(): void;
    ngOnChanges(changes: SimpleChanges): boolean;
    arraysEqual(attrValue: any, hostValue: any): boolean;
    manageAttributes(): any;
    moveClasses(parentEl: HTMLElement, childEl: HTMLElement): void;
    moveStyles(parentEl: HTMLElement, childEl: HTMLElement): void;
    createComponent(options?: any): void;
    createWidget(options?: any): void;
    __updateRect__(): void;
    setOptions(options: any): void;
    animationDuration(arg?: number): number;
    barSize(arg?: number | string): number | string;
    description(arg?: string): string;
    disabled(arg?: boolean): boolean;
    height(arg?: string | number): string | number;
    labelsFormat(arg?: string): string;
    labelsFormatFunction(arg?: (value?: jqwidgets.BulletChartLabelsFormatFunction['value'], position?: jqwidgets.BulletChartLabelsFormatFunction['position']) => any): (value?: jqwidgets.BulletChartLabelsFormatFunction['value'], position?: jqwidgets.BulletChartLabelsFormatFunction['position']) => any;
    orientation(arg?: string): string;
    pointer(arg?: jqwidgets.BulletChartPointer): jqwidgets.BulletChartPointer;
    rtl(arg?: boolean): boolean;
    ranges(arg?: Array<jqwidgets.BulletChartRanges>): Array<jqwidgets.BulletChartRanges>;
    showTooltip(arg?: boolean): boolean;
    target(arg?: jqwidgets.BulletChartPointer): jqwidgets.BulletChartPointer;
    ticks(arg?: jqwidgets.BulletChartTicks): jqwidgets.BulletChartTicks;
    title(arg?: string): string;
    tooltipFormatFunction(arg?: (pointerValue?: jqwidgets.BulletChartTooltipFormatFunction['pointerValue'], targetValue?: jqwidgets.BulletChartTooltipFormatFunction['targetValue']) => string): (pointerValue?: jqwidgets.BulletChartTooltipFormatFunction['pointerValue'], targetValue?: jqwidgets.BulletChartTooltipFormatFunction['targetValue']) => string;
    width(arg?: string | number): string | number;
    destroy(): void;
    render(): void;
    refresh(): void;
    val(value?: number): any;
    onChange: EventEmitter<any>;
    __wireEvents__(): void;
}
