/// <reference path="../jqwidgets.d.ts" />
import { AfterViewInit, AfterViewChecked, EventEmitter, ElementRef, OnChanges, SimpleChanges } from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
export declare class jqxComboBoxComponent implements ControlValueAccessor, OnChanges, AfterViewInit, AfterViewChecked {
    attrAnimationType: string;
    attrAutoComplete: boolean;
    attrAutoOpen: boolean;
    attrAutoItemsHeight: boolean;
    attrAutoDropDownHeight: boolean;
    attrCloseDelay: number;
    attrCheckboxes: boolean;
    attrDisabled: boolean;
    attrDisplayMember: string;
    attrDropDownHorizontalAlignment: string;
    attrDropDownVerticalAlignment: string;
    attrDropDownHeight: number | string;
    attrDropDownWidth: number | string;
    attrEnableHover: boolean;
    attrEnableSelection: boolean;
    attrEnableBrowserBoundsDetection: boolean;
    attrItemHeight: number;
    attrMultiSelect: boolean;
    attrMinLength: number;
    attrOpenDelay: number;
    attrPopupZIndex: number;
    attrPlaceHolder: string;
    attrRemoteAutoComplete: boolean;
    attrRemoteAutoCompleteDelay: number;
    attrRenderer: (index?: jqwidgets.ComboBoxRenderer['index'], label?: jqwidgets.ComboBoxRenderer['label'], value?: jqwidgets.ComboBoxRenderer['value']) => string;
    attrRenderSelectedItem: (index?: jqwidgets.ComboBoxRenderSelectedItem['index'], item?: jqwidgets.ComboBoxRenderSelectedItem['item']) => string;
    attrRtl: boolean;
    attrSelectedIndex: number;
    attrShowArrow: boolean;
    attrShowCloseButtons: boolean;
    attrSearchMode: string;
    attrSearch: (searchString?: jqwidgets.ComboBoxSearch['searchString']) => void;
    attrSource: any;
    attrScrollBarSize: number | string;
    attrTemplate: string;
    attrTheme: string;
    attrValidateSelection: (itemValue?: jqwidgets.ComboBoxValidateSelection['itemValue']) => boolean;
    attrValueMember: string;
    attrWidth: string | number;
    attrHeight: string | number;
    autoCreate: boolean;
    properties: string[];
    host: any;
    elementRef: ElementRef;
    widgetObject: jqwidgets.jqxComboBox;
    content: String;
    container: HTMLDivElement;
    private onTouchedCallback;
    private onChangeCallback;
    constructor(containerElement: ElementRef);
    ngOnInit(): void;
    ngAfterViewInit(): void;
    ngAfterViewChecked(): void;
    ngOnChanges(changes: SimpleChanges): boolean;
    arraysEqual(attrValue: any, hostValue: any): boolean;
    manageAttributes(): any;
    moveClasses(parentEl: HTMLElement, childEl: HTMLElement): void;
    moveStyles(parentEl: HTMLElement, childEl: HTMLElement): void;
    createComponent(options?: any): void;
    createWidget(options?: any): void;
    __updateRect__(): void;
    writeValue(value: any): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    setOptions(options: any): void;
    animationType(arg?: string): string;
    autoComplete(arg?: boolean): boolean;
    autoOpen(arg?: boolean): boolean;
    autoItemsHeight(arg?: boolean): boolean;
    autoDropDownHeight(arg?: boolean): boolean;
    closeDelay(arg?: number): number;
    checkboxes(arg?: boolean): boolean;
    disabled(arg?: boolean): boolean;
    displayMember(arg?: string): string;
    dropDownHorizontalAlignment(arg?: string): string;
    dropDownVerticalAlignment(arg?: string): string;
    dropDownHeight(arg?: number | string): number | string;
    dropDownWidth(arg?: number | string): number | string;
    enableHover(arg?: boolean): boolean;
    enableSelection(arg?: boolean): boolean;
    enableBrowserBoundsDetection(arg?: boolean): boolean;
    height(arg?: string | number): string | number;
    itemHeight(arg?: number): number;
    multiSelect(arg?: boolean): boolean;
    minLength(arg?: number): number;
    openDelay(arg?: number): number;
    popupZIndex(arg?: number): number;
    placeHolder(arg?: string): string;
    remoteAutoComplete(arg?: boolean): boolean;
    remoteAutoCompleteDelay(arg?: number): number;
    renderer(arg?: (index?: jqwidgets.ComboBoxRenderer['index'], label?: jqwidgets.ComboBoxRenderer['label'], value?: jqwidgets.ComboBoxRenderer['value']) => string): (index?: jqwidgets.ComboBoxRenderer['index'], label?: jqwidgets.ComboBoxRenderer['label'], value?: jqwidgets.ComboBoxRenderer['value']) => string;
    renderSelectedItem(arg?: (index?: jqwidgets.ComboBoxRenderSelectedItem['index'], item?: jqwidgets.ComboBoxRenderSelectedItem['item']) => string): (index?: jqwidgets.ComboBoxRenderSelectedItem['index'], item?: jqwidgets.ComboBoxRenderSelectedItem['item']) => string;
    rtl(arg?: boolean): boolean;
    selectedIndex(arg?: number): number;
    showArrow(arg?: boolean): boolean;
    showCloseButtons(arg?: boolean): boolean;
    searchMode(arg?: string): string;
    search(arg?: (searchString?: jqwidgets.ComboBoxSearch['searchString']) => void): (searchString?: jqwidgets.ComboBoxSearch['searchString']) => void;
    source(arg?: any): any;
    scrollBarSize(arg?: number | string): number | string;
    template(arg?: string): string;
    theme(arg?: string): string;
    validateSelection(arg?: (itemValue?: jqwidgets.ComboBoxValidateSelection['itemValue']) => boolean): (itemValue?: jqwidgets.ComboBoxValidateSelection['itemValue']) => boolean;
    valueMember(arg?: string): string;
    width(arg?: string | number): string | number;
    addItem(item: any): boolean;
    clearSelection(): void;
    clear(): void;
    close(): void;
    checkIndex(index: number): void;
    checkItem(item: any): void;
    checkAll(): void;
    destroy(): void;
    disableItem(item: any): void;
    disableAt(index: number): void;
    enableItem(item: any): void;
    enableAt(index: number): void;
    ensureVisible(index: number): void;
    focus(): void;
    getItem(index: number): any;
    getItemByValue(value: string): any;
    getVisibleItems(): Array<any>;
    getItems(): Array<any>;
    getCheckedItems(): Array<any>;
    getSelectedItem(): any;
    getSelectedItems(): Array<any>;
    getSelectedIndex(): number;
    insertAt(item: any, index: number): boolean;
    isOpened(): boolean;
    indeterminateIndex(index: number): void;
    indeterminateItem(item: any): void;
    loadFromSelect(selectTagId: string): void;
    open(): void;
    removeItem(item: any): boolean;
    removeAt(index: number): boolean;
    selectIndex(index: number): void;
    selectItem(item: any): void;
    searchString(): string;
    updateItem(item: any, itemValue: string): void;
    updateAt(item: any, index: any): void;
    unselectIndex(index: number): void;
    unselectItem(item: any): void;
    uncheckIndex(index: number): void;
    uncheckItem(item: any): void;
    uncheckAll(): void;
    val(value?: string): any;
    onBindingComplete: EventEmitter<any>;
    onCheckChange: EventEmitter<any>;
    onClose: EventEmitter<any>;
    onChange: EventEmitter<any>;
    onOpen: EventEmitter<any>;
    onSelect: EventEmitter<any>;
    onUnselect: EventEmitter<any>;
    __wireEvents__(): void;
}
