/// <reference path="../jqwidgets.d.ts" />
import { EventEmitter, ElementRef, OnChanges, SimpleChanges } from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
export declare class jqxMaskedInputComponent implements ControlValueAccessor, OnChanges {
    attrDisabled: boolean;
    attrMask: string;
    attrPromptChar: number | string;
    attrReadOnly: boolean;
    attrRtl: boolean;
    attrTheme: string;
    attrTextAlign: string;
    attrValue: number | string;
    attrWidth: string | number;
    attrHeight: string | number;
    autoCreate: boolean;
    properties: string[];
    host: any;
    elementRef: ElementRef;
    widgetObject: jqwidgets.jqxMaskedInput;
    private onTouchedCallback;
    private onChangeCallback;
    constructor(containerElement: ElementRef);
    ngOnInit(): void;
    ngOnChanges(changes: SimpleChanges): boolean;
    arraysEqual(attrValue: any, hostValue: any): boolean;
    manageAttributes(): any;
    moveClasses(parentEl: HTMLElement, childEl: HTMLElement): void;
    moveStyles(parentEl: HTMLElement, childEl: HTMLElement): void;
    createComponent(options?: any): void;
    createWidget(options?: any): void;
    __updateRect__(): void;
    writeValue(value: any): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    setOptions(options: any): void;
    disabled(arg?: boolean): boolean;
    height(arg?: string | number): string | number;
    mask(arg?: string): string;
    promptChar(arg?: number | string): number | string;
    readOnly(arg?: boolean): boolean;
    rtl(arg?: boolean): boolean;
    theme(arg?: string): string;
    textAlign(arg?: string): string;
    value(arg?: number | string): number | string;
    width(arg?: string | number): string | number;
    clear(): void;
    destroy(): void;
    focus(): void;
    val(value?: number | string): any;
    onChange: EventEmitter<any>;
    onValueChanged: EventEmitter<any>;
    __wireEvents__(): void;
}
