/// <reference path="../jqwidgets.d.ts" />
import { EventEmitter, ElementRef, OnChanges, SimpleChanges } from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
export declare class jqxPasswordInputComponent implements ControlValueAccessor, OnChanges {
    attrDisabled: boolean;
    attrLocalization: jqwidgets.PasswordInputLocalization;
    attrMaxLength: number | string;
    attrPlaceHolder: number | string;
    attrPasswordStrength: (password: jqwidgets.PasswordInputPasswordStrength['password'], characters: jqwidgets.PasswordInputPasswordStrength['characters'], defaultStrength: jqwidgets.PasswordInputPasswordStrength['defaultStrength']) => string;
    attrRtl: boolean;
    attrStrengthColors: jqwidgets.PasswordInputStrengthColors;
    attrShowStrength: boolean;
    attrShowStrengthPosition: string;
    attrStrengthTypeRenderer: (password: jqwidgets.PasswordInputStrengthTypeRenderer['password'], characters: jqwidgets.PasswordInputStrengthTypeRenderer['characters'], defaultStrength: jqwidgets.PasswordInputStrengthTypeRenderer['defaultStrength']) => string;
    attrShowPasswordIcon: boolean;
    attrTheme: string;
    attrWidth: string | number;
    attrHeight: string | number;
    autoCreate: boolean;
    properties: string[];
    host: any;
    elementRef: ElementRef;
    widgetObject: jqwidgets.jqxPasswordInput;
    private onTouchedCallback;
    private onChangeCallback;
    constructor(containerElement: ElementRef);
    ngOnInit(): void;
    ngOnChanges(changes: SimpleChanges): boolean;
    arraysEqual(attrValue: any, hostValue: any): boolean;
    manageAttributes(): any;
    moveClasses(parentEl: HTMLElement, childEl: HTMLElement): void;
    moveStyles(parentEl: HTMLElement, childEl: HTMLElement): void;
    createComponent(options?: any): void;
    createWidget(options?: any): void;
    __updateRect__(): void;
    ngValue: any;
    writeValue(value: any): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    setOptions(options: any): void;
    disabled(arg?: boolean): boolean;
    height(arg?: string | number): string | number;
    localization(arg?: jqwidgets.PasswordInputLocalization): jqwidgets.PasswordInputLocalization;
    maxLength(arg?: number | string): number | string;
    placeHolder(arg?: number | string): number | string;
    passwordStrength(arg?: (password: jqwidgets.PasswordInputPasswordStrength['password'], characters: jqwidgets.PasswordInputPasswordStrength['characters'], defaultStrength: jqwidgets.PasswordInputPasswordStrength['defaultStrength']) => string): (password: jqwidgets.PasswordInputPasswordStrength['password'], characters: jqwidgets.PasswordInputPasswordStrength['characters'], defaultStrength: jqwidgets.PasswordInputPasswordStrength['defaultStrength']) => string;
    rtl(arg?: boolean): boolean;
    strengthColors(arg?: jqwidgets.PasswordInputStrengthColors): jqwidgets.PasswordInputStrengthColors;
    showStrength(arg?: boolean): boolean;
    showStrengthPosition(arg?: string): string;
    strengthTypeRenderer(arg?: (password: jqwidgets.PasswordInputStrengthTypeRenderer['password'], characters: jqwidgets.PasswordInputStrengthTypeRenderer['characters'], defaultStrength: jqwidgets.PasswordInputStrengthTypeRenderer['defaultStrength']) => string): (password: jqwidgets.PasswordInputStrengthTypeRenderer['password'], characters: jqwidgets.PasswordInputStrengthTypeRenderer['characters'], defaultStrength: jqwidgets.PasswordInputStrengthTypeRenderer['defaultStrength']) => string;
    showPasswordIcon(arg?: boolean): boolean;
    theme(arg?: string): string;
    width(arg?: string | number): string | number;
    render(): void;
    refresh(): void;
    val(value?: string): any;
    onChange: EventEmitter<any>;
    __wireEvents__(): void;
}
